[package]
name = "rpg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chbs_password_checker = "0.1.0"
prettytable-rs = "0.8.0"
rand = "0.8.4"
structopt = "0.3.22"
zxcvbn = "2.1.1"
